### ISSUE TITLE
setting up full request caching 

### ISSUE THREAD

**Issue by mrbookt** [heyday/silverstripe-cacheinclude#24]
I have a problem with setting up full request caching. I am using sample config provided in the docs and I am getting error:

`[User Error] Uncaught RuntimeException: Config 'Global' doesn't exist, please check your config`

There is a 'Global' var in constructor part of yml config.

SS 3.41 / silverstripe-cacheinclude": "~4.0"

**Comment by camspiers** [comment]
You need to add a "Global" key to your config. e.g.

```yml
---
After: 'silverstripe-cacheinclude/*'
---
Injector:
  CacheIncludeConfig:
    class: Heyday\CacheInclude\Configs\ArrayConfig
    properties:
      Config:
        Global:
          context: full
          expires: +1 hour
```
